version: '3.1'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: mobtitude/php-xdebug:7.1-fpm
    volumes:
      - ./src:/src
    networks:
      - code-network
  nodejs:
    image: node
    ports:
      - "49999:49999"
    environment:
      NODE_ENV: development
    working_dir: /home/app
    restart: always
    volumes:
      - ./nodejs:/home/app
    command: bash -c "npm install --no-bin-links && npm start"

networks:
  code-network:
    driver: bridge
