version: '3.1'

services:
    web:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./src:/src
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: mobtitude/php-xdebug:7.1-fpm
        volumes:
            - ./src:/src
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
